version: '3'

services:
  pgsql-test:
    container_name: pgsql-test
    image: postgres
    environment:
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "db_password"
      POSTGRES_DB: "db_test"
      PGDATA: "/var/lib/postgresql/data/data_db_test"
    ports:
      - "5432"
    networks:
      - my-prj-net
    volumes:
      - pgsql_data:/var/lib/postgresql/data/data_db_test
  
  flask-test:
    container_name: flask-test
    build: ./flask/
    ports:
      - "5050:5050"
    networks:
      - my-prj-net
    depends_on:
      - pgsql-test
  

networks:
  my-prj-net:
    driver: bridge

volumes:
  pgsql_data:
