{
 "title": "My Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Node's",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Self Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=\"exporter:9100\", cpu=\"0\", mode=\"idle\"}[5m]))*100)",
     "legendFormat": "CPU - 1"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=\"exporter:9100\", cpu=\"1\", mode=\"idle\"}[5m]))*100)",
     "legendFormat": "CPU - 2"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=\"exporter:9100\", cpu=\"2\", mode=\"idle\"}[5m]))*100)",
     "legendFormat": "CPU - 3"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=\"exporter:9100\", cpu=\"3\", mode=\"idle\"}[5m]))*100)",
     "legendFormat": "CPU - 4"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"exporter:9100\"} - node_memory_MemFree_bytes{instance=\"exporter:9100\"}) / node_memory_MemTotal_bytes{instance=\"exporter:9100\"}) * 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"exporter:9100\"} - node_memory_SwapFree_bytes{instance=\"exporter:9100\"}) / node_memory_SwapTotal_bytes{instance=\"exporter:9100\"}) * 100",
     "legendFormat": "swap"
    }
   ]
  },
  {
   "title": "Main DIsk",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes{instance=\"exporter:9100\", device=\"/dev/sda2\"} - node_filesystem_free_bytes{instance=\"exporter:9100\", device=\"/dev/sda2\"}) / node_filesystem_size_bytes{instance=\"exporter:9100\", device=\"/dev/sda2\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"exporter:9100\", device=\"eth0\"}[$__interval])",
     "legendFormat": "receive {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"exporter:9100\", device=\"eth0\"}[$__interval])",
     "legendFormat": "transmit {{device}}"
    }
   ]
  },
  {
   "title": "Main Disk Write Troughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"exporter:9100\", device=\"sda\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Main Disk Read Troughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"exporter:9100\", device=\"sda\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "(rate(node_disk_write_time_seconds_total{instance=\"exporter:9100\", device=\"sda\"}[$__rate_interval]) * 1000) / rate(node_disk_writes_completed_total{instance=\"exporter:9100\", device=\"sda\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "(rate(node_disk_read_time_seconds_total{instance=\"exporter:9100\", device=\"sda\"}[$__rate_interval]) * 1000) / rate(node_disk_reads_completed_total{instance=\"exporter:9100\", device=\"sda\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Workunit Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=\"workunit.test.by:9100\", cpu=\"0\", mode=\"idle\"}[5m]))*100)",
     "legendFormat": "CPU - 1"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=\"workunit.test.by:9100\", cpu=\"1\", mode=\"idle\"}[5m]))*100)",
     "legendFormat": "CPU - 2"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 11, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"workunit.test.by:9100\"} - node_memory_MemFree_bytes{instance=\"workunit.test.by:9100\"}) / node_memory_MemTotal_bytes{instance=\"workunit.test.by:9100\"}) * 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"workunit.test.by:9100\"} - node_memory_SwapFree_bytes{instance=\"workunit.test.by:9100\"}) / node_memory_SwapTotal_bytes{instance=\"workunit.test.by:9100\"}) * 100",
     "legendFormat": "swap"
    }
   ]
  },
  {
   "title": "Main DIsk",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes{instance=\"workunit.test.by:9100\", device=\"/dev/sda2\"} - node_filesystem_free_bytes{instance=\"workunit.test.by:9100\", device=\"/dev/sda2\"}) / node_filesystem_size_bytes{instance=\"workunit.test.by:9100\", device=\"/dev/sda2\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"workunit.test.by:9100\", device=\"eth0\"}[$__interval])",
     "legendFormat": "receive {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"workunit.test.by:9100\", device=\"eth0\"}[$__interval])",
     "legendFormat": "transmit {{device}}"
    }
   ]
  },
  {
   "title": "Main Disk Write Troughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"workunit.test.by:9100\", device=\"sda\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Main Disk Read Troughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"workunit.test.by:9100\", device=\"sda\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "(rate(node_disk_write_time_seconds_total{instance=\"workunit.test.by:9100\", device=\"sda\"}[$__rate_interval]) * 1000) / rate(node_disk_writes_completed_total{instance=\"workunit.test.by:9100\", device=\"sda\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "(rate(node_disk_read_time_seconds_total{instance=\"workunit.test.by:9100\", device=\"sda\"}[$__rate_interval]) * 1000) / rate(node_disk_reads_completed_total{instance=\"workunit.test.by:9100\", device=\"sda\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}