version: '3.9'

services:
  pgsql_test:
    container_name: pgsql_test
    build: ./db/
    expose:
      - 5432
    networks:
      - my_prj_back
    volumes:
      - pgsql_data:/var/lib/postgresql/data/data_db_test
  
  flask_test:
    container_name: flask_test
    build: ./flask/
    expose:
      - 5050
    # ports:
    #   - 5050:5050
    networks:
      - my_prj_front
      - my_prj_back
    depends_on:
      - pgsql_test
  
  nginx_test:
    container_name: nginx_test
    build: ./nginx/
    ports:
      - 80:80
      - 443:443
    networks:
      - my_prj_front
    depends_on:
      - flask_test


networks:
  my_prj_back:
    driver: bridge
  my_prj_front:
    driver: bridge

volumes:
  pgsql_data:
