scrape_configs:
  - job_name: self-node
    scrape_interval: 5s
    static_configs:
    - targets: ['exporter:9100']
  - job_name: node-workunit
    scrape_interval: 5s
    static_configs:
    - targets: ['workunit.test.by:9100']


rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

